### ISSUE TITLE
Config  oauth unused properties

### ISSUE THREAD

**Issue by RoboSparrow** [Brightcookie/lxHive#199]
The following OAuth properties seem not to be used in the code
```    
oauth:
        reauthorize_time: 0
        reauthenticate_time: 2592000
#...
```

can I safely remove them?
