### ISSUE TITLE
Documents API: Concurrency validation is not backwards compatible (xAPI Version header, config.yml)

### ISSUE THREAD

**Issue by RoboSparrow** [Brightcookie/lxHive#23]
Submitted requests who are requiring eTags in xAPI 1.03. should not require this:

- when sent as former xAPI versions.
- the LRS is configured for support lower than 1.0.3
- when sent in legacy (IE) mode (POST ?method=<method>)

Currently any affected request are validated as 1.0.3, regardless of `X-Experience-API-Version` header or supported version settings in the Config.yml

Endpoints:

```
/agents
/activities/state
/activities
```

Config.yml, set to 1.0.1 but still having issue:
```
name: myGPcommunity
mode: development
database:
    host_uri: 'mongodb://127.0.0.1'
    db_name: lxHive
xAPI:
    latest_version: 1.0.1
    statement_get_limit: 100
    default_statement_get_format: exact
    supported_versions: [1.0.1,1.0.0]
    supported_auth_scopes: [{ name: super, description: 'Administrate the LRS' }, { name: statements/read, description: 'Read statements' }, { name: statements/read/mine, description: 'Read own statements' }, { name: attachments, description: 'Include attachments' }, { name: state, description: 'Access the State API' }, { name: profile, description: 'Access the Profile API' }, { name: define, description: '(Re)define new Activities' }, { name: all/read, description: 'Full read-only access' }, { name: all, description: 'Full access' }]
    oauth: { reauthorize_time: 0, reauthenticate_time: 2592000, branding: { enabled: false, logo_path: null, header: null, footer: null, css_path: null } }
filesystem:
    exposed_url: /attachments
    in_use: local
    local: { root_dir: '%app.root%/storage/files' }
```
**Also: we need to honour the [legacy request mode](https://github.com/adlnet/xAPI-Spec/blob/1.0.3/xAPI.md#alt-request-syntax) in the same way:**

i.e `POST https://api.experience.at/activities/state?method=GET` (returns a 500 with irrelevant CORS error message)

ADL example of CORS PUT request: https://github.com/adlnet/xAPI-Spec/blob/1.0.3/xAPI.md#appendix-g-cross-domain-request-example

Since applications like storyline send in legacy mode and *don't supply a version param* we have in this case to revert to the minimal supported version as defined in config.yml

@kienv @MarcusFabriczy can give you more details
